name: Booking Genius Deployment

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
          extensions: mbstring, zip, intl, gd, pdo_mysql, exif, pcntl, bcmath, soap, sockets, opcache, mysqli, pdo, pdo_pgsql, pgsql, redis, imagick, mongodb, apcu, memcached, xdebug
          # i insall composer /project 
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer -o composer-setup.php
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          rm composer-setup.php
          composer install --prefer-dist --no-progress --no-suggest --no-interaction --optimize-autoloader --no-scripts
          # i insall composer /project

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Set up environment variables
        run: |
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4

        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /booking.geniusocean.xyz/ # Change this to your shared hosting's web directory
          run: vendor/bin/phpunit
