name: Booking Genius Deployment

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"
          # i need cd project folder and install composer

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-suggest
        working-directory: project

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        working-directory: project

      - name: Set up environment variables in .env existing file
        run: |
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=${{ secrets.DB_DATABASE }}/g' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=${{ secrets.DB_USERNAME }}/g' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/g' .env
        working-directory: project

      - name: Generate Application Key
        run: php artisan key:generate
        working-directory: project

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4

        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          passive: true
