name: Booking Genius Deployment

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
          extensions: mbstring, zip, intl, gd, pdo_mysql, exif, pcntl, bcmath, soap, sockets, opcache, mysqli, pdo, pdo_pgsql, pgsql, redis, imagick, mongodb, apcu, memcached, xdebug
          
          
          # i need cd project folder and install composer
        
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: project

     

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Set up environment variables
        run: |
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4

        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # booking.geniusocean.xyz
          server-dir: home/geniusxyz/booking.geniusocean.xyz
          run: vendor/bin/phpunit
